log_pin = "1768"

google_sheet_id = "1rKTShTm607R2Cb6HY7gcDKddP2Rxrcq9cIQeHMwQLx4"
google_worksheet_name = "CarWash"

[gcp_service_account]
type = "service_account"
project_id = "carwash-478809"
private_key_id = "7a690badd00e4717a06b167e7103e7a20e5a55be"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDwC5ou6jk4BV0n
bfaegLMKaM01RlhCA288NsGVcRq67+5WylyIWQmpojTYvmKL8Jz8OS95cCjJn2gZ
it5u5nxHtk+tQkl6V/zUesOnquZtV+iMCmCvRfZbDHtR7vYg7wplybCDKJEJjyet
d1c/ydEMglYh0fkItrtkFEROmSKnXcev58H8d0nfI9MwDcRweBBXXb64NC3OzqAC
7/082ik3QYXxUY/o/cPiZs5tMmldeKLfCOY9p2X76N8/9twjkrnBxzjzsd2QKhja
A7Gd6zGEWdi2qWAjTekvw3wDUCf9X2mBUsrQPg/fXpiyT7e3D3pl5IhK6Q4dBCeY
o13kDhiNAgMBAAECggEAYkddyPd8lcMccJhE8IAgzZI68iTq3ZwqXqzMdTLpjr/N
BRu05t4NZrZSjKrmDgVlQJ7pIP8as/Hf3RVOHHmhSHsMBBOvobeEfDoHAQ6naP0k
6LEXBKvQQVbK5rC/dJxp1WLOMeTZ/N/vjsXdovAt9sEmIpKlMzwdXMwvaz6nQX4I
wxuQbOwJ3kkJCWH38DrNckoV0dIh4Y5nlF4kev1ekfhohe0iaaVmIhcq915LcRy4
WJEK4pfF18B18PSLXDcu/+i7/Gx5i6OVjVdIuGMWQCmjYN3IKPLUqQTEezSxlSCb
qEIgm1FY6mZFcme4cpiFJJPZpklErYczo419NcOYwQKBgQD+0Uo95kUwc1UnubKs
W7RYkzUkRRD5B8UikShlQQleci50tiEEui9FEUbSKR0o1rePYTMKQuLhGIhuQjvi
xoGB0YODXXXfNH+sD/avhpd+b1nQdwk9Zim93jW8Yt59KosCE2B/bNxbjGt49Wcz
1H5elw0m6dJZgSRPSNXatM8oBwKBgQDxKMN+NHRwVcwoT1L9pqzXi8HxWUNheEPe
gXLJWzTXckUJnUq4dMzRe9E+iBQBBzXrI/xLiNzc+Ux3PIYJ18bE7DjB5w9cntxU
0Fb8wFq8Dr4NVqpHAZPvNnGvI/GfINCUh8QbyOCr9/nXmkhuQy/yd3ANBI2EnF8l
mr6yoPcNywKBgBqaSv/vXGXUhJ1jG6423Lsqky+4Li9xijkzol3/zjSYAxWYNhZC
QdEaHqSuOicbU4qagTOfDASoBQZNz+a7BqZA81Pxm+6zkmiqOfzVNley1FOZOdO5
KL5zxnRmdgfnOx/6WeazvMWqAUZdiGq20oKZjnvziUxi2SGV3w24NrBdAoGBANx9
eMAbFZrf1xnD7Q0dJ0qr7VbNVl33p5X4pQqU6WtSfuybc4XSxLGDk3yoziFihlnH
PRWSvN0M0mzyWVsGfiXuFLa0m8cDOFATbHULKepnUDzB0E27k5ZTIP4Qzwm+5vXm
a9c7gq+4uiX2WeL2axA1Q62jTADDN/sZ0OFhaoChAoGBAN6vAV3y/T8IDSW8jLBl
hWeR2+u28qdX6j4fV6fZcEwTav1TWVZXmw3nR6EHVnkPtTFURBkybefqWdCwGkyj
7KLU7wmYNqfCd8YkkIfa6a58F+zkG9PGSt1sDDbG3CEP/bI4VXaqSpA0EHpuuan3
JEX3ocbkqdGwsc0L1vIpq2Ls
-----END PRIVATE KEY-----"""
client_email = "carwash@carwash-478809.iam.gserviceaccount.com"
client_id = "109087062953972341534"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/carwash%40carwash-478809.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
